# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  - 7.0
  - 7.1
  - 7.2

services:
    - riak
    - mongodb
    - memcached
    - redis-server
    - docker

before_install:
    - pecl channel-update pecl.php.net
    - echo yes | pecl upgrade apcu


# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-source --no-interaction

script:
  - phpunit $PHPUNIT_FLAGS